name: FancySelect
author: lorenzo.stanco
category: Interface
tags: [dropdown, select, image, drop, down]
demo: http://www.lorenzostanco.com/demos/FancySelect/Demo.html
docs: http://wiki.github.com/lorenzos/FancySelect/docs
current: 0.2
sources:
  - "Source/FancySelect.js"